# Day 008: Introduction to Matrices (Shapes, Tensors, and Image Representation)


## 1. Objective
> To programmatically create and manipulate **Matrices (2D Tensors)** and **3D Tensors** using ***NumPy***. You will learn to inspect tensor attributes `(shape, dimensions, memory size)` and visualize numerical grids as real images using ***Matplotlib***.

## 2. Mathematical Foundation
> In code, a Tensor is implemented as an N-dimensional array. NumPy gives us crucial properties to understand our mathematical structures without printing out millions of numbers:  
> * `.ndim`: *Returns the number of dimensions* (e.g., 2 for a matrix, 3 for an RGB image).  
> * `.shape`: *Returns a tuple representing the exact size of each dimension* `(Rows, Columns, Channels)`.  
> * `.size`: *Returns the total number of scalar elements inside the entire tensor*.

## 3. Real-World & AI Applications
> **Computer Vision (CNNs):**  
> When you load an image in Python using libraries like OpenCV or PIL, it doesn't load a "picture file." It loads a NumPy array (Tensor). If an image has a shape of `(1080, 1920, 3)`, a **Convolutional Neural Network (CNN)** mathematically slides a smaller "filter" matrix across these rows and columns to detect edges, faces, and objects.  
> **Data Flattening:**  
> Classic neural network layers (Dense/Linear layers) cannot process 2D or 3D grids. The tensor must be mathematically unrolled into a single 1D vector. In *NumPy*, this is done using `.flatten()`, which converts a shape of `(28, 28)` into `(784,)`.

## 4. Algorithmic Strategy
> To master tensors in NumPy, we must be comfortable constructing them from scratch:  
> i. **Create** nested Python lists: A list of lists creates a *2D Matrix*. A list of lists of lists creates a *3D Tensor*.  
> ii. **Convert** the lists to NumPy arrays using `np.array()`.  
> iii. **Inspect** the tensor using `.shape` and `.ndim` to guarantee the AI gets the geometry it expects.  
> iv. **Manipulate** the dimensions using operations like `.flatten()`.

## 5. Implementation

In [4]:
import numpy as np


# --- 1. Creating a 2D Matrix (Grayscale Image Representation) ---
# A 3x3 grid where 0 is black, 255 is white, and numbers in between are gray.
gray_data = [
    [0, 128, 255],
    [255, 0, 128],
    [128, 255, 0]
]

matrix_2d = np.array(gray_data)

print("--- 2D Matrix Analysis ---")
print(f"Matrix Data:\n{matrix_2d}")
print(f"Dimensions (.ndim): {matrix_2d.ndim}D")
print(f"Shape (.shape): {matrix_2d.shape} (Rows, Columns)")
print(f"Total Elements (.size): {matrix_2d.size}\n\n")


# --- 2. Flattening the Matrix ---
# Unrolling the 2D grid into a 1D vector for a Dense Neural Network Layer
flattened_vector = matrix_2d.flatten()

print("--- Flatten Vector Analysis ---")
print(f"Flattened Data:\n{flattened_vector}")
print(f"Dimensions (.ndim): {flattened_vector.ndim}D")
print(f"Shape (.shape): {flattened_vector.shape} (Rows, Columns)")
print(f"Total Elements (.size): {flattened_vector.size}\n\n")

# --- 3. Creating a 3D Tensor (RGB Image Representation) ---
# Shape will be (3, 3, 3) -> 3 rows, 3 columns, 3 color channels
# Let's create a solid red block, a solid green block, and a solid blue block

rgb_data = [
    # Row 1 (Red pixel, Green pixel, Blue pixel)
    [[255, 0, 0], [0, 255, 0], [0, 0, 255]],
    
    # Row 2 (Blue pixel, Red pixel, Green pixel)
    [[0, 0, 255], [255, 0, 0], [0, 255, 0]],
    
    # Row 3 (Green pixel, Blue pixel, Red pixel)
    [[0, 255, 0], [0, 0, 255], [255, 0, 0]]
]

tensor_3d = np.array(rgb_data)

print("\n--- 3D Tensor Analysis ---")
print(f"3D Tensor Data:\n{tensor_3d}")
print(f"Dimensions (.ndim): {tensor_3d.ndim}D")
print(f"Shape (.shape): {tensor_3d.shape} (Height, Width, Channels)")
print(f"Total Elements (.size): {tensor_3d.size}")


--- 2D Matrix Analysis ---
Matrix Data:
[[  0 128 255]
 [255   0 128]
 [128 255   0]]
Dimensions (.ndim): 2D
Shape (.shape): (3, 3) (Rows, Columns)
Total Elements (.size): 9


--- Flatten Vector Analysis ---
Flattened Data:
[  0 128 255 255   0 128 128 255   0]
Dimensions (.ndim): 1D
Shape (.shape): (9,) (Rows, Columns)
Total Elements (.size): 9



--- 3D Tensor Analysis ---
3D Tensor Data:
[[[255   0   0]
  [  0 255   0]
  [  0   0 255]]

 [[  0   0 255]
  [255   0   0]
  [  0 255   0]]

 [[  0 255   0]
  [  0   0 255]
  [255   0   0]]]
Dimensions (.ndim): 3D
Shape (.shape): (3, 3, 3) (Height, Width, Channels)
Total Elements (.size): 27


## 6. Verification

In [ ]:
# Write a small test block proving your scratch code works
# Compare it against a known mathematical outcome if possible


## 7. Complexity Analysis
- **Time Complexity:** `O(...)` *(Explain why)*
- **Space Complexity:** `O(...)` *(Explain why)*